import { QuestionnaireSection } from '../types';

export const QUESTIONNAIRE_SECTIONS: QuestionnaireSection[] = [
  {
    id: 'diet',
    title: 'Your Diet',
    description: 'Tell us about your eating habits and food preferences.',
    questions: [
      {
        id: 'diet_quality',
        text: 'How would you describe your average meal?',
        type: 'select',
        options: [
          { value: 'very_poor', label: 'Mostly processed foods, fast food, high in sugar and fat' },
          { value: 'poor', label: 'Some processed foods, occasional vegetables and fruits' },
          { value: 'average', label: 'Mix of whole foods and processed foods' },
          { value: 'good', label: 'Mostly whole foods, vegetables, fruits, lean proteins' },
          { value: 'excellent', label: 'Balanced diet rich in vegetables, fruits, whole grains, lean proteins' },
        ],
        required: true,
      },
      {
        id: 'meal_frequency',
        text: 'How many meals do you eat per day?',
        type: 'number',
        min: 1,
        max: 10,
        required: true,
      },
      {
        id: 'vegetable_servings',
        text: 'How many servings of vegetables do you eat daily?',
        type: 'number',
        min: 0,
        max: 20,
        required: true,
      },
      {
        id: 'fruit_servings',
        text: 'How many servings of fruit do you eat daily?',
        type: 'number',
        min: 0,
        max: 20,
        required: true,
      },
      {
        id: 'protein_source',
        text: 'What is your primary source of protein?',
        type: 'select',
        options: [
          { value: 'red_meat', label: 'Red meat (beef, pork, lamb)' },
          { value: 'poultry', label: 'Poultry (chicken, turkey)' },
          { value: 'fish', label: 'Fish and seafood' },
          { value: 'dairy_eggs', label: 'Dairy and eggs' },
          { value: 'plant_based', label: 'Plant-based (beans, lentils, tofu)' },
        ],
        required: true,
      },
    ],
  },
  {
    id: 'sleep',
    title: 'Sleep Habits',
    description: 'Let\'s understand your sleep patterns and quality.',
    questions: [
      {
        id: 'sleep_duration',
        text: 'How many hours do you sleep on average per night?',
        type: 'number',
        min: 1,
        max: 16,
        step: 0.5,
        required: true,
      },
      {
        id: 'sleep_quality',
        text: 'How would you rate your sleep quality?',
        type: 'select',
        options: [
          { value: 'very_poor', label: 'Very poor - I wake up feeling exhausted' },
          { value: 'poor', label: 'Poor - I often wake up tired' },
          { value: 'average', label: 'Average - I wake up feeling okay' },
          { value: 'good', label: 'Good - I usually wake up feeling rested' },
          { value: 'excellent', label: 'Excellent - I consistently wake up feeling refreshed' },
        ],
        required: true,
      },
      {
        id: 'sleep_consistency',
        text: 'How consistent is your sleep schedule?',
        type: 'select',
        options: [
          { value: 'very_inconsistent', label: 'Very inconsistent - bedtime and wake time vary by hours' },
          { value: 'inconsistent', label: 'Inconsistent - bedtime and wake time vary by 1-2 hours' },
          { value: 'somewhat_consistent', label: 'Somewhat consistent - occasional variations' },
          { value: 'consistent', label: 'Consistent - same schedule most days' },
          { value: 'very_consistent', label: 'Very consistent - same schedule every day' },
        ],
        required: true,
      },
      {
        id: 'wakeups',
        text: 'How often do you wake up during the night?',
        type: 'select',
        options: [
          { value: 'never', label: 'Never or rarely' },
          { value: 'occasionally', label: 'Occasionally (1-2 times per week)' },
          { value: 'sometimes', label: 'Sometimes (3-4 times per week)' },
          { value: 'frequently', label: 'Frequently (5-7 times per week)' },
          { value: 'multiple', label: 'Multiple times every night' },
        ],
        required: true,
      },
    ],
  },
  {
    id: 'work',
    title: 'Work Environment',
    description: 'Tell us about your work and daily activities.',
    questions: [
      {
        id: 'work_type',
        text: 'What type of work do you do?',
        type: 'select',
        options: [
          { value: 'sedentary', label: 'Sedentary (desk job, minimal movement)' },
          { value: 'light_activity', label: 'Light activity (standing, walking occasionally)' },
          { value: 'moderate_activity', label: 'Moderate activity (regular movement, some physical tasks)' },
          { value: 'heavy_activity', label: 'Heavy activity (physically demanding work)' },
          { value: 'not_employed', label: 'Not currently employed / retired' },
        ],
        required: true,
      },
      {
        id: 'work_hours',
        text: 'How many hours do you work per week?',
        type: 'number',
        min: 0,
        max: 100,
        required: true,
        dependsOn: {
          questionId: 'work_type',
          value: ['sedentary', 'light_activity', 'moderate_activity', 'heavy_activity'],
        },
      },
      {
        id: 'work_stress',
        text: 'How would you rate your work-related stress level?',
        type: 'select',
        options: [
          { value: 'very_low', label: 'Very low - rarely feel stressed' },
          { value: 'low', label: 'Low - occasionally feel stressed' },
          { value: 'moderate', label: 'Moderate - sometimes feel stressed' },
          { value: 'high', label: 'High - often feel stressed' },
          { value: 'very_high', label: 'Very high - constantly feel stressed' },
        ],
        required: true,
        dependsOn: {
          questionId: 'work_type',
          value: ['sedentary', 'light_activity', 'moderate_activity', 'heavy_activity'],
        },
      },
      {
        id: 'sitting_hours',
        text: 'How many hours do you spend sitting per day?',
        type: 'number',
        min: 0,
        max: 24,
        required: true,
      },
    ],
  },
  {
    id: 'exercise',
    title: 'Physical Activity',
    description: 'Let\'s understand your exercise habits and physical activity.',
    questions: [
      {
        id: 'exercise_frequency',
        text: 'How many days per week do you engage in intentional exercise?',
        type: 'number',
        min: 0,
        max: 7,
        required: true,
      },
      {
        id: 'exercise_duration',
        text: 'On days you exercise, how many minutes do you typically spend?',
        type: 'number',
        min: 0,
        max: 300,
        required: true,
        dependsOn: {
          questionId: 'exercise_frequency',
          value: [1, 2, 3, 4, 5, 6, 7],
        },
      },
      {
        id: 'exercise_intensity',
        text: 'What is the typical intensity of your exercise?',
        type: 'select',
        options: [
          { value: 'light', label: 'Light (walking, gentle yoga)' },
          { value: 'moderate', label: 'Moderate (brisk walking, cycling, swimming)' },
          { value: 'vigorous', label: 'Vigorous (running, HIIT, heavy weightlifting)' },
          { value: 'mixed', label: 'Mixed (combination of different intensities)' },
        ],
        required: true,
        dependsOn: {
          questionId: 'exercise_frequency',
          value: [1, 2, 3, 4, 5, 6, 7],
        },
      },
      {
        id: 'strength_training',
        text: 'How many days per week do you do strength training?',
        type: 'number',
        min: 0,
        max: 7,
        required: true,
      },
    ],
  },
  {
    id: 'habits',
    title: 'Lifestyle Habits',
    description: 'Tell us about your other lifestyle habits.',
    questions: [
      {
        id: 'smoking',
        text: 'Do you smoke tobacco products?',
        type: 'select',
        options: [
          { value: 'never', label: 'Never smoked' },
          { value: 'former', label: 'Former smoker' },
          { value: 'occasional', label: 'Occasional smoker (less than daily)' },
          { value: 'light', label: 'Light smoker (1-9 cigarettes per day)' },
          { value: 'moderate', label: 'Moderate smoker (10-19 cigarettes per day)' },
          { value: 'heavy', label: 'Heavy smoker (20+ cigarettes per day)' },
        ],
        required: true,
      },
      {
        id: 'alcohol',
        text: 'How many alcoholic drinks do you consume per week?',
        type: 'number',
        min: 0,
        max: 100,
        required: true,
      },
      {
        id: 'screen_time',
        text: 'How many hours per day do you spend on screens (outside of work)?',
        type: 'number',
        min: 0,
        max: 24,
        required: true,
      },
      {
        id: 'social_connection',
        text: 'How would you rate your level of social connection?',
        type: 'select',
        options: [
          { value: 'very_low', label: 'Very low - isolated, rarely interact with others' },
          { value: 'low', label: 'Low - limited social interactions' },
          { value: 'moderate', label: 'Moderate - some friends and family connections' },
          { value: 'high', label: 'High - strong social network, regular interactions' },
          { value: 'very_high', label: 'Very high - extensive social connections, very active social life' },
        ],
        required: true,
      },
    ],
  },
]; 